---
services:
  ldap-service:
    build: . 
    environment:
      NODE_ENV: production
      NODE_PORT: ${SERVER_PORT}
    env_file:
      - env/.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-fk", "${SERVER_HOSTNAME}:${SERVER_PORT}/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 3