FROM node:alpine-lts

# Production Dockerfile
# Deps - copy package.json and install modules
# Builder - copy modules from Deps, compile typescript
# Runner - copy modules, dist and run


# Dev dockerfile
# Copy package.json && install deps
# Run yarn tsc && node --watch dist/index.js